### ISSUE TITLE
How to use your repository?

### ISSUE THREAD

**Issue by CaoTrongThang** [Pure-Peace/pp-server#4]
I've downloaded the .exe file and run it but nothing happen.

**Comment by Pure-Peace** [comment]
Yes, in addition to that, you need to download `project.zip` and extract the files in it to the same directory as the executable, after that it will work

[https://github.com/Pure-Peace/pp-server/releases/download/v0.5.0/project.zip](https://github.com/Pure-Peace/pp-server/releases/download/v0.5.0/project.zip)

Unfortunately, this repository is currently not actively maintained, and the pp version used is relatively backward, so it is not recommended to use it.

**Comment by CaoTrongThang** [comment]
> 

Thanks bro, I'm using it, but there's a mods field that requires number, I don't really know what it means, I thought mods are like DT HD EZ,... like that, what number should i use if i want to check beatmap pp with DT and HD?

This is what I got from osu api
![image](https://user-images.githubusercontent.com/51023235/196091744-04576223-6640-43fa-8379-34a6ea9cb468.png)
