### ISSUE TITLE
Please help me with mods number

### ISSUE THREAD

**Issue by CaoTrongThang** [Pure-Peace/pp-server#5]
There's a mods query that requires number, I don't really know what it means, I thought mods are like DT HD EZ,... like that, what number should i use if i want to check beatmap pp with DT and HD or many more mods?

![image](https://user-images.githubusercontent.com/51023235/196129829-92d699d4-53ca-4987-924f-2f155e933e2f.png)

**Comment by Pure-Peace** [comment]
[https://github.com/ppy/osu-api/wiki#mods](https://github.com/ppy/osu-api/wiki#mods)

You can refer to here, if there are multiple mods, you need to perform a bitwise OR operation on the numbers (HDDT=8 | 64)

**Comment by CaoTrongThang** [comment]
Jesus, thanks bro, you're sooo good at reading documents, i've try to read osu document like in few days but still bad af, thanks again <3
